name: 'Setup Saucectl'
description: 'Setup saucectl and adding it to the PATH'
author: 'felix@saucelabs.com'
inputs:
  saucectl-version:
    description: 'Version Spec of the version to use.  Examples: v0.18.x, v0.18.1, >=v0.19.0'
runs:
  using: 'node12'
  main: 'src/index.js'