blank_issues_enabled: false
contact_links:
  - name: 🤔 Documentation
    url: https://docs.saucelabs.com/
    about: Before filing an issue, please consult the documentation first. You just might find your answer right there!
