name: Tests

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: install devDependencies
        run: npm ci
      - name: run the tests
        run: npm test
      - name: build new dist
        run: npx ncc build src/index.js -o dist/reference
      - name: compare actual build with expected
        run: diff -U 5 dist/reference/index.js dist/main/index.js